repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format papersai
        language: system
        types: [python]
      - id: ruff-check
        name: ruff-check
        entry: ruff check --fix papersai
        language: system
        types: [python]
